Use the new requestMatchers with Spring Security 5.8 - partially resolves #255 (#286)
* WIP on #255 - replace `antMatchers` - test only fails due to whitespace

Strangely when removing/adding lines a type failure in the AST occurs:

```
java.lang.IllegalStateException: AST contains missing or invalid type information
MethodInvocation->MethodInvocation->MethodInvocation->MethodInvocation->MethodInvocation->MethodInvocation->Lambda->MethodInvocation->Block->MethodDeclaration->Block->ClassDeclaration->CompilationUnit
/*~~(type information has a different method name 'antMatchers')~~>*/authz
                        .requestMatchers("/api/admin/**")
```

* WIP on #255 - remove the blank line to match the expected output.

Still trying to figure out the type issue

* WIP 225 some progres made. mvcMatchers needs a different treatment
because it is abstract so we'll need to find the `requestMatchers` in
the supertype in that case

* WIP 225 all tests pass :)

* Override getSingleSourceApplicableTest to limit execution early

* Apply formatter to trim trailing text block whitespace

* Minimize before and after samples

* 255 Use optional as return type for more expressiveness

* 255 - skip unnecessary null check for methodType

Method matchers should guard against this case.

And even if we did get null: Most users will run this in the context of Spring Boot 3 migrations where helpful NPEs are already part of JDK17

Co-authored-by: Tim te Beek <timtebeek@gmail.com>

* 255 refactor gradle build

* 255 use dependencies from resources

---------

Co-authored-by: Tim te Beek <tim@moderne.io>
Co-authored-by: Tim te Beek <timtebeek@gmail.com>