WIP on #255 - replace `antMatchers` - test only fails due to whitespace
Strangely when removing/adding lines a type failure in the AST occurs:

```
java.lang.IllegalStateException: AST contains missing or invalid type information
MethodInvocation->MethodInvocation->MethodInvocation->MethodInvocation->MethodInvocation->MethodInvocation->Lambda->MethodInvocation->Block->MethodDeclaration->Block->ClassDeclaration->CompilationUnit
/*~~(type information has a different method name 'antMatchers')~~>*/authz
                        .requestMatchers("/api/admin/**")
```