2025.0.x Incompatible with Spring Boot 4.0 (NoSuchMethodError) (#971)
* 2025.0.x Incompatible with Spring Boot 4.0 (NoSuchMethodError)

* Polish, as separate steps no longer needed

* Recreate recipes.csv

---------

Co-authored-by: Tim te Beek <tim@moderne.io>